
volumes:
  pg_tracker:
    name: pg_tracker_db_volume
    external: false

services:
  tracker_db:
    container_name: ${TRACKER_DB_NAME}
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${TRACKER_DB_USER}
      - POSTGRES_PASSWORD=${TRACKER_DB_PASSWORD}
      - POSTGRES_DB=${TRACKER_DB_NAME}
    volumes:
      - pg_tracker:/var/lib/postgresql/data

    ports:
      - ${TRACKER_DB_HOST}:${TRACKER_DB_EPORT}:${TRACKER_DB_PORT}

  app:
    restart: always
    build:
      context: ${APP_PATH}
      dockerfile: Dockerfile
    ports:
      - ${TRACKER_APP_EPORT}:${TRACKER_APP_PORT}
    depends_on:
      - tracker_db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_APPLICATION_JSON: ${SPRING_APPLICATION_PARAMS}
      JAVA_OPTS: ${JV_MAX_MEM}
