version: '3.1'

volumes:
  pg_tracker:

services:
  tracker_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=tracker_db
    volumes:
      - pg_tracker:/var/lib/postgresql/data

    ports:
      - "127.0.0.1:5433:5432"

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - tracker_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://tracker_db:5432/tracker_db'
      JAVA_OPTS: '-Xmx512m'
